---
- name: Check for required variables
  fail:
    msg: 'Variable {{ item }} is not defined'
  when: item not in vars
  loop: '{{ required_vars }}'
- name: Install nginx
  package:
    name: nginx
    state: present
- name: Add nginx conf
  ansible.builtin.copy:
    src: '{{ nginx_conf }}'
    dest: /etc/nginx/sites-available/default
- name: Start nginx.service
  ansible.builtin.systemd:
    state: restarted
    name: nginx.service
