---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v4.3.7
    hooks:
      - id: ansible-lint
