- name: Install and configure Azure pipeline agent software
  hosts: all
  become: yes
  vars_files:
    - "./vars/secrets.yaml"
  vars:
    agent_version: 2.175.0
    pool: Default
    user: azure
  roles:
    - custom_sudo_user
    - docker      
    - azure_pipeline_agent