---
- name: Add new user
  include_role:
    name: regular_user
  vars:
    user: '{{ new_user }}'
- name: Add new user to Jupyterhub conf
  ansible.builtin.replace:
    path: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
    regexp: '^c.Authenticator.allowed_users = {(.*)}$'
    replace: 'c.Authenticator.allowed_users = {\1,"{{ new_user }}"}'
- name: Restart jupyterhub.service
  ansible.builtin.systemd:
    state: restarted
    name: jupyterhub.service
