---
- name: Check for required variables
  fail:
    msg: 'Variable {{ item }} is not defined'
  when: item not in vars
  loop: '{{ required_vars }}'
- name: Add user
  user:
    name: '{{ user }}'
    state: present
- name: Allow paswordless sudo with user
  ansible.builtin.copy:
    content: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/{{ user }}
    # sudoers.d/username file is preferred over sudoers,
    # since the latter is changed by system updates
    validate: 'visudo -cf %s'
