- name: Add user
  user:
    name: '{{ user }}'
    group: admin    
- name: Allow paswordless sudo with user
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
