- name: Install Azure CLI
  pip:
    name: azure-cli  
    executable: pip3
    state: present
- name: Download and extract Azure DevOps agent software 
  become_user: '{{ user }}'
  ansible.builtin.unarchive:
    remote_src: yes        
    src: https://vstsagentpackage.azureedge.net/agent/{{ agent_version }}/vsts-agent-linux-x64-{{ agent_version }}.tar.gz
    dest: /home/{{ user }}
    creates: /home/{{ user }}/config.sh
- name: Configure Azure DevOps agent
  become_user: '{{ user }}'
  command: >
    ./config.sh 
    --unattended
    --acceptTeeEula
    --url={{ url }}
    --auth pat
    --token={{ token}}
  args:
    chdir: /home/{{ user }}
    creates: .agent
- name: Install Azure DevOps agent
  become_user: '{{ user }}'
  command: >
    sudo
    ./svc.sh 
    install
  args:
    chdir: /home/{{ user }}
    creates: .service
- name: Get Azure DevOps agent systemd name
  shell: cat /home/{{ user }}/.service
  register: azure_devops_systemd
- name: Run Azure DevOps agent
  ansible.builtin.systemd:
    state: started
    name: '{{ azure_devops_systemd.stdout }}'