---
- name: Check required variables
  fail:
    msg: 'Variable {{ item }} is not defined'
  when: item not in vars
  loop: '{{ required_vars }}'
- name: Add user
  user:
    name: '{{ user }}'
    password: "{{ 'changeme'|password_hash('sha512') }}"
    update_password: on_create
    state: present
