---
- name: Set up Jupyterhub server
  hosts: all
  become: yes
  vars:
    jupyter_path: /opt/jupyterhub
  tasks:
    - name: Add jupyter admin user
      include_role:
        name: regular_user
      vars:
        user: jupyter
    - name: Install and configure Jupyterhub
      include_role:
        name: jupyterhub
      vars:
        admin_user: jupyter
    - name: Install and configure Conda
      include_role:
        name: conda
    - name: Install and configure Nginx
      include_role:
        name: nginx
      vars:
        nginx_conf: ./nginx_jupyterhub_conf
    - name: Add new user(s)
      tags:
        - adduser
      include_tasks:
        file: add_user.yaml
        apply:
          tags:
            - adduser
      with_items:
        - user_1  # Change this
      loop_control:
        loop_var: new_user
