---
- name: Set up Jupyterhub server
  hosts: all
  become: yes
  vars:
    jupyter_path: /opt/jupyterhub
  tasks:
    - name: Add jupyter admin user
      include_role:
        name: regular_user
        vars_from: secrets  # Add user password
      vars:
        user: jupyter
    - name: Install and configure Jupyterhub
      include_role:
        name: jupyterhub
      vars:
        admin_user: jupyter
    - name: Install and configure Conda
      include_role:
        name: conda
    - name: Install and configure Nginx
      include_role:
        name: nginx
      vars:
        nginx_conf: nginx_jupyterhub_conf
    - name: Add new user(s) to Jupyterhub
      tags: add_user
      include_role:
        name: jupyterhub
        tasks_from: add_user
        apply:
          tags: add_user
      with_items: '{{ new_users }}'
      loop_control:
        loop_var: new_user
