---
- name: Install and configure Azure pipeline agents
  hosts: all
  become: yes
  vars_files:
    - './secrets.yaml'
  vars:
    # agent_version: 2.181.1  # optional
    # pool: self-hosted  # optional
    user: azure
  roles:
    - custom_sudo_user
    - docker
    - azure_pipeline_agent
